### ISSUE TITLE
Problem - ui-sref or $state.go redirect to the same state with different parameter

### ISSUE THREAD

**Issue by michDostal** [vizo/angular-ui-router-i18n#3]
Hi,

I'm writing angular app with ui-router & angular-ui-router-i18n.
When I'm going between different states everything runs well, but if i'm on a state and I'm trying go to the same state but with different parameter I ends up with this error -> http://prntscr.com/7l2c5e

http://www.whiteisbrightblack.cz/swnmoravia/cs/kategorie/combined
http://prntscr.com/7l2pa5

I tried use only ui-router also with ui-router-extras but its the same...

Thank you for reply and have a nice day.
M.D.

**Comment by nicompte** [comment]
Hello, I submitted a pull request that should solve this problem: #4.

**Comment by michDostal** [comment]
@nicompte
Hey man! You are amazing... it really works.
Thank you

**Comment by vizo** [comment]
Merged, sorry for late response.
